apiVersion: v2
name: otelcollector
description: A Helm chart for managing otel-collector
type: application
version: 0.1.0
appVersion: 0.61.0
dependencies:
# cert manager must be manually installed because it has CRDs
# https://github.com/kubernetes-sigs/security-profiles-operator/issues/1062
# - name: opentelemetry-operator
#   repository: https://open-telemetry.github.io/opentelemetry-helm-charts
#   version: 0.15.0
#   condition: observability.otelcol.enabled
