apiVersion: v2
name: otelcollector
description: Deprecated chart for using the OpenTelemetry Collector to scape static or dynamic metric targets.
type: application
version: 0.2.1
appVersion: 0.83.0
deprecated: true
dependencies:
# cert manager must be manually installed because it has CRDs
# https://github.com/kubernetes-sigs/security-profiles-operator/issues/1062
# - name: opentelemetry-operator
#   repository: https://open-telemetry.github.io/opentelemetry-helm-charts
#   version: 0.15.0
#   condition: observability.otelcol.enabled
